name: 'Test srcML libsrcml'
description: 'Run srcML libsrcml tests and upload test logs'
inputs:
  prefix:
    description: 'Prefix for artifact names'
    required: true
  working-directory:
    description: 'Working directory for tests'
    required: false
    default: 'build'

runs:
  using: 'composite'
  steps:
    - name: Test libsrcml
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      shell: bash
      run: |
        cmake --build . --target test_libsrcml
    
    - name: Upload LastTest.log
      uses: actions/upload-artifact@v4
      if: ${{ hashFiles('Testing/Temporary/LastTest.log') != '' }}
      with:
        name: ${{ inputs.prefix }}-libsrcml_last_test.log
        path: ${{ inputs.working-directory }}/Testing/Temporary/LastTest.log
    
    - name: Upload libsrcml logs
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: ${{ inputs.prefix }}-libsrcml.log
        path: ${{ inputs.working-directory }}/dist/*-libsrcml.log
