---
name: Build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.0

      - name: Build and package
        shell: bash
        run: |
          cmake --workflow --preset ci-macos

      - name: Run Installed srcml
        shell: bash
        run: |
          srcml --version
          srcml --text="int a;" -l C++
