---
name: Build macOS

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.0

      - name: Configure
        shell: bash
        run: |
          cmake --preset ci-macos

      - name: Build
        shell: bash
        run: |
          cmake --build --preset ci-macos

      - name: Package
        shell: bash
        run: |
          cd ../srcML-build
          cpack

      - name: Install package
        shell: bash
        working-directory: ../srcML-build/dist
        run: |
          sudo installer -dumplog -pkg srcml-1.1.0-macOS.pkg -target /

      - name: Run Installed srcml
        shell: bash
        run: |
          srcml --version
          srcml --text="int a;" -l C++

      - name: Test client
        working-directory: ../srcML-build
        continue-on-error: true
        shell: bash
        run: |
          ctest -R ^srcml -VV

      - name: Test libsrcml
        working-directory: ../srcML-build
        continue-on-error: true
        shell: bash
        run: |
          ctest -R ^libsrcml -VV

      - name: Test parser
        working-directory: ../srcML-build
        continue-on-error: true
        shell: bash
        run: |
          ninja run_parser_tests

      - name: Build
        shell: bash
        run: |
          cmake --preset ci-macos -DCMAKE_OSX_ARCHITECTURES=x86_64 -U CMAKE_OSX_ARCHITECTURES
          cmake --build --preset ci-macos

      - name: Package
        working-directory: ../srcML-build
        shell: bash
        run: |
          cpack

      - name: Build
        shell: bash
        run: |
          cmake --preset ci-macos -DCMAKE_OSX_ARCHITECTURES=arm64 -U CMAKE_OSX_ARCHITECTURES
          cmake --build --preset ci-macos

      - name: Package
        working-directory: ../srcML-build
        shell: bash
        run: |
          cpack

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: |
            /Users/runner/work/srcML/srcML-build/dist/*.pkg
            /Users/runner/work/srcML/srcML-build/dist/*.tar.gz
            /Users/runner/work/srcML/srcML-build/dist/*.tar.bz2
