name: Test Client

on:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y curl zip g++ make ninja-build antlr libantlr-dev \
                              libxml2-dev libxml2-utils libxslt1-dev \
                              libarchive-dev libssl-dev libcurl4-openssl-dev \
                              cpio man file dpkg-dev

      - name: Setup macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install antlr
          sudo xcode-select -s /Library/Developer/CommandLineTools

      - name: Setup Windows (msys2)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: zip cpio diffutils cmake util-linux libxml2

      - name: Setup Windows (vcpkg)
        if: matrix.os == 'windows-latest'
        uses: ./.github/actions/vcpkg
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Install (Ubuntu/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          cmake --preset ci-${{ matrix.os == 'ubuntu-latest' && 'ubuntu' || 'macos' }} -B build
          sudo cmake --build build --config Release --target install
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then sudo ldconfig; fi

      - name: Build and Install (Windows)
        if: matrix.os == 'windows-latest'
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: ci-msvc

      - name: Prepare Tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          # Patch Test Framework for Windows
          sed -i '/^compare() {/a \    [ -f "$1" ] && sed -i "s|\\\\|/|g" "$1"; [ -f "$2" ] && sed -i "s|\\\\|/|g" "$2"' test/client/testsuite/framework_test.sh
          # Replace /dev/stdin with - for native xmllint compatibility
          sed -i 's|/dev/stdin|-|g' test/client/testsuite/*.sh
          
          # Add necessary paths to GITHUB_PATH
          echo "${{ github.workspace }}/build/vcpkg_installed/x64-windows/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/build/bin/Release" >> $GITHUB_PATH
          echo "C:/msys64/usr/bin" >> $GITHUB_PATH

      - name: Run Tests (Ubuntu/macOS)
        if: matrix.os != 'windows-latest'
        working-directory: build
        run: ctest -VV --rerun-failed --output-on-failure

      - name: Run Tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        env:
          MSYS: winsymlinks:nativestrict
          MSYS2_ARG_CONV_EXCL: "*"
        working-directory: build
        run: |
          export SRCML_HOME="C:/srcML"
          
          # Force MSYS2 bash to output Windows style paths to match the srcml native binary output
          echo "pwd() { builtin pwd -W; }" > bash_env.sh
          export BASH_ENV="$(pwd)/bash_env.sh"
          
          "/c/Program Files/CMake/bin/ctest.exe" -C Release -VV

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestLogs-${{ matrix.os }}
          path: |
            build/Testing/Temporary/LastTest.log
            build/**/*.xml
          if-no-files-found: ignore

      - name: Upload Failure Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: FailureArtifacts-${{ matrix.os }}
          path: |
            build/Testing/
            build/test/
          if-no-files-found: ignore
