name: Test Client 2

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  test:
    name: Build and Test Client
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Define the OS matrix
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Map each OS to its corresponding CMake preset
        include:
          - os: ubuntu-latest
            preset: ci-ubuntu
          - os: macos-latest
            preset: ci-macos
          - os: windows-latest
            preset: ci-msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: ./.github/actions/vcpkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Build Directory
        run: mkdir build

      - name: Run CMake (Configure and Build)
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: ${{ matrix.preset }}

      - name: Run CTest
        working-directory: build
        run: ctest --output-on-failure -V
